// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 从前 limit 个元素中查找 timestamps 重合的元素
Future<Map<PlatformInt64, BigInt>> findCandlestickIndices(
        {required List<Candlestick> list,
        required Set<PlatformInt64> timestamps,
        required BigInt limit}) =>
    RustLib.instance.api.crateApiCalculatorFindCandlestickIndices(
        list: list, timestamps: timestamps, limit: limit);

/// 计算给定蜡烛图列表的价格范围
/// Return (max_price, min_price)
Future<(double, double)> findCandlesticksPriceRange(
        {required List<Candlestick> candlesticks}) =>
    RustLib.instance.api.crateApiCalculatorFindCandlesticksPriceRange(
        candlesticks: candlesticks);

String greet({required String name}) =>
    RustLib.instance.api.crateApiCalculatorGreet(name: name);
